name: UFC Scraper

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run scraper script
        run: python ./scripts/scrape_ufc.py

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Convert CSV to RData
        run: |
          ufc_data <- read.csv("./data/ufc_data.csv")
          save(ufc_data, file = "./data/ufc_data.RData")
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add ./data/ufc_data.csv ./data/ufc_data.RData

          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Automated update of UFC data"
            git pull --rebase origin main
            git push
          fi
